/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    patients: Patient;
    doctors: Doctor;
    healthStatuses: HealthStatus;
    histories: History;
    diagnoses: Diagnosis;
    reminders: Reminder;
    appointments: Appointment;
    messages: Message;
    referrals: Referral;
    recurrencePlans: RecurrencePlan;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    patients: PatientsSelect<false> | PatientsSelect<true>;
    doctors: DoctorsSelect<false> | DoctorsSelect<true>;
    healthStatuses: HealthStatusesSelect<false> | HealthStatusesSelect<true>;
    histories: HistoriesSelect<false> | HistoriesSelect<true>;
    diagnoses: DiagnosesSelect<false> | DiagnosesSelect<true>;
    reminders: RemindersSelect<false> | RemindersSelect<true>;
    appointments: AppointmentsSelect<false> | AppointmentsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    referrals: ReferralsSelect<false> | ReferralsSelect<true>;
    recurrencePlans: RecurrencePlansSelect<false> | RecurrencePlansSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  clerkId: string;
  username: string;
  fname: string;
  lname: string;
  imageUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string[];
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  _key?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patients".
 */
export interface Patient {
  id: string;
  user: string | User;
  DOB: string;
  gender?: ('Male' | 'Female' | 'Other') | null;
  maritalStatus?: ('Single' | 'Married' | 'Divorced' | 'Widowed' | 'Separated') | null;
  occupation?: string | null;
  race?: string | null;
  language?: string[] | null;
  emergencyContacts?:
    | {
        name: string;
        relationship: string;
        phone: string;
        priority?: ('1' | '2' | '3' | '4' | '5') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors".
 */
export interface Doctor {
  id: string;
  user: string | User;
  DOB: string;
  gender?: ('Male' | 'Female' | 'Other') | null;
  language?: string[] | null;
  bio?: string | null;
  specialties?:
    | {
        primary:
          | 'General Practice'
          | 'Internal Medicine'
          | 'Pediatrics'
          | 'Obstetrics & Gynecology'
          | 'Cardiology'
          | 'Endocrinology'
          | 'Gastroenterology'
          | 'Pulmonology'
          | 'Nephrology'
          | 'Neurology'
          | 'Psychiatry'
          | 'Dermatology'
          | 'Ophthalmology'
          | 'Otolaryngology (ENT)'
          | 'Orthopedic Surgery'
          | 'Rheumatology'
          | 'Hematology'
          | 'Oncology'
          | 'Infectious Disease'
          | 'Immunology'
          | 'Allergy'
          | 'Urology'
          | 'General Surgery'
          | 'Plastic Surgery'
          | 'Cardiothoracic Surgery'
          | 'Neurosurgery'
          | 'Vascular Surgery'
          | 'Anesthesiology'
          | 'Radiology'
          | 'Nuclear Medicine'
          | 'Pathology'
          | 'Emergency Medicine'
          | 'Critical Care'
          | 'Family Medicine'
          | 'Geriatrics'
          | 'Sports Medicine'
          | 'Occupational Medicine'
          | 'Palliative Care'
          | 'Dentistry'
          | 'Other';
        secondary?:
          | (
              | 'General Practice'
              | 'Internal Medicine'
              | 'Pediatrics'
              | 'Obstetrics & Gynecology'
              | 'Cardiology'
              | 'Endocrinology'
              | 'Gastroenterology'
              | 'Pulmonology'
              | 'Nephrology'
              | 'Neurology'
              | 'Psychiatry'
              | 'Dermatology'
              | 'Ophthalmology'
              | 'Otolaryngology (ENT)'
              | 'Orthopedic Surgery'
              | 'Rheumatology'
              | 'Hematology'
              | 'Oncology'
              | 'Infectious Disease'
              | 'Immunology'
              | 'Allergy'
              | 'Urology'
              | 'General Surgery'
              | 'Plastic Surgery'
              | 'Cardiothoracic Surgery'
              | 'Neurosurgery'
              | 'Vascular Surgery'
              | 'Anesthesiology'
              | 'Radiology'
              | 'Nuclear Medicine'
              | 'Pathology'
              | 'Emergency Medicine'
              | 'Critical Care'
              | 'Family Medicine'
              | 'Geriatrics'
              | 'Sports Medicine'
              | 'Occupational Medicine'
              | 'Palliative Care'
              | 'Dentistry'
              | 'Other'
            )
          | null;
        procedures: string[];
        id?: string | null;
      }[]
    | null;
  credentials: {
    medicalCertifications?:
      | {
          type?: ('MD' | 'DO' | 'MBBS' | 'MBChB' | 'DDS' | 'DMD' | 'PhD' | 'Other') | null;
          institution: string;
          date: string;
          name: string;
          id?: string | null;
        }[]
      | null;
    licenses?:
      | {
          licenseNumber: string;
          type?: ('Permanent' | 'Training' | 'Provisional') | null;
          status?: ('Active' | 'Inactive' | 'Suspended' | 'Revoked' | 'Expired') | null;
          issuingState: string;
          expirationDate: string;
          id?: string | null;
        }[]
      | null;
    boardCertifications?:
      | {
          boardName: string;
          certificationId: string;
          status?: ('Active' | 'Inactive' | 'Suspended' | 'Revoked' | 'Expired') | null;
          date: string;
          expirationDate?: string | null;
          id?: string | null;
        }[]
      | null;
    hospitalAffiliations?:
      | {
          name: string;
          department: string;
          roles: string[];
          startDate: string;
          endDate?: string | null;
          id?: string | null;
        }[]
      | null;
    isVerified?: boolean | null;
  };
  contact: {
    officialPhone: string;
    officialEmail: string;
    mobilePhone?: string | null;
  };
  metrics?: {
    numberOfPatients?: number | null;
    readmissionRate?: number | null;
    experience?: number | null;
    rating?:
      | {
          user: string | User;
          rating?: ('1' | '2' | '3' | '4' | '5') | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "healthStatuses".
 */
export interface HealthStatus {
  id: string;
  patient: string | Patient;
  vitals: {
    bloodPressure: string;
    heartRate: string;
    temperature: string;
    respiratoryRate: string;
    oxygenSaturation: string;
    weight: string;
    bmi: string;
  };
  complaint?: string | null;
  symptoms?:
    | {
        description?: string | null;
        severity: '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10';
        duration?: string | null;
        onset: string;
        id?: string | null;
      }[]
    | null;
  pain?:
    | {
        location: string;
        intensity: '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10';
        type: 'Sharp' | 'Dull' | 'Burning' | 'Aching';
        aggravatingFactors?: string[] | null;
        relievingFactors?: string[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "histories".
 */
export interface History {
  id: string;
  patient: string | Patient;
  diseaseHistory?:
    | {
        name: string;
        diagnosisDate: string;
        resolved: boolean;
        resolutionDate?: string | null;
        id?: string | null;
      }[]
    | null;
  surgicalHistory?:
    | {
        procedure: string;
        date: string;
        facility: string;
        id?: string | null;
      }[]
    | null;
  familyHistory?:
    | {
        condition: string;
        relation: string;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  allergies?:
    | {
        substance: string;
        reaction: string;
        severity: 'Mild' | 'Moderate' | 'Severe';
        onsetDate?: string | null;
        lastReactionDate?: string | null;
        id?: string | null;
      }[]
    | null;
  socialHistory: {
    smoking?: {
      status?: ('Never' | 'Occasional' | 'Regular' | 'Former') | null;
      years?: number | null;
      quiteDate?: string | null;
      lastUser?: string | null;
    };
    alcohol?: {
      status?: ('Never' | 'Occasional' | 'Regular' | 'Former') | null;
      years?: number | null;
      quiteDate?: string | null;
      lastUser?: string | null;
    };
    substanceUse: {
      substances: string[];
      status?: ('Never' | 'Occasional' | 'Regular' | 'Former') | null;
      quiteDate?: string | null;
      lastUser?: string | null;
    };
  };
  exercise?: string | null;
  diet?: string | null;
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "diagnoses".
 */
export interface Diagnosis {
  id: string;
  appointment: string | Appointment;
  patient: string | Patient;
  doctor: string | Doctor;
  healthStatus: string | HealthStatus;
  history: string | History;
  chiefComplaint?: string | null;
  preAppointmentNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  medicationsReviewed?: boolean | null;
  templateUsed?: string | null;
  onsetDate: string;
  dateResolved?: string | null;
  status?: ('Active' | 'Provisional' | 'Ruled-out' | 'Confirmed' | 'Resolved' | 'Pending') | null;
  updatedBy?: (string | null) | Doctor;
  differentialDiagnosis?:
    | {
        condition: string;
        icd10Code?: string | null;
        reasoning: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        isPrimary?: boolean | null;
        confidence: 'Ruled-out' | 'Low' | 'Medium' | 'High' | 'Confirmed';
        laterality?: ('Left' | 'Right' | 'Bilateral') | null;
        severity: 'Mild' | 'Moderate' | 'Severe';
        dateConfirmed: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments".
 */
export interface Appointment {
  id: string;
  patient: string | Patient;
  doctor?: (string | null) | Doctor;
  diagnosis?: (string | null) | Diagnosis;
  healthStatus?: (string | null) | HealthStatus;
  reminders?: (string | Reminder)[] | null;
  reason: string;
  type:
    | 'Consultation'
    | 'Follow Up'
    | 'New Patient'
    | 'Annual Exam'
    | 'Post Op'
    | 'Procedure'
    | 'Telemedicine'
    | 'Phone Consult';
  status?:
    | ('Scheduled' | 'Confirmed' | 'Cancelled' | 'Arrived' | 'In Progress' | 'Completed' | 'No Show' | 'Rescheduled')
    | null;
  confirmation?: {
    isConfirmed?: boolean | null;
    confirmedAt?: string | null;
    confirmedBy?: (string | null) | User;
  };
  cancellation?: {
    cancelledAt?: boolean | null;
    cancelledBy?: (string | null) | User;
    reason?: string | null;
  };
  startTime?: string | null;
  endTime?: string | null;
  patientNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  doctorNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  followUpInstructions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  consentLevels?: ('Health statuses' | 'Vitals' | 'History' | 'Patient profile' | 'User profile')[] | null;
  isEmergency?: boolean | null;
  online: {
    url: string;
    accessCode?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reminders".
 */
export interface Reminder {
  id: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  appointment: string | Appointment;
  body: string;
  status?: ('Sent' | 'Received' | 'Read') | null;
  refMessage?: (string | null) | Message;
  from: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referrals".
 */
export interface Referral {
  id: string;
  appointment: string | Appointment;
  from: string | Doctor;
  to: string | Doctor;
  reason: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status?: ('Pending' | 'Active' | 'Rejected' | 'Completed' | 'Cancelled') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recurrencePlans".
 */
export interface RecurrencePlan {
  id: string;
  supervisor: string | Doctor;
  appointment: string | Appointment;
  name: string;
  frequency: 'Daily' | 'Weekly' | 'Bi-weekly' | 'Monthly';
  interval: number;
  startDate: string;
  endDate?: string | null;
  startTime: string;
  endTime?: string | null;
  weekDays: ('Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday')[];
  exceptions?:
    | {
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'patients';
        value: string | Patient;
      } | null)
    | ({
        relationTo: 'doctors';
        value: string | Doctor;
      } | null)
    | ({
        relationTo: 'healthStatuses';
        value: string | HealthStatus;
      } | null)
    | ({
        relationTo: 'histories';
        value: string | History;
      } | null)
    | ({
        relationTo: 'diagnoses';
        value: string | Diagnosis;
      } | null)
    | ({
        relationTo: 'reminders';
        value: string | Reminder;
      } | null)
    | ({
        relationTo: 'appointments';
        value: string | Appointment;
      } | null)
    | ({
        relationTo: 'messages';
        value: string | Message;
      } | null)
    | ({
        relationTo: 'referrals';
        value: string | Referral;
      } | null)
    | ({
        relationTo: 'recurrencePlans';
        value: string | RecurrencePlan;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  clerkId?: T;
  username?: T;
  fname?: T;
  lname?: T;
  imageUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _key?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patients_select".
 */
export interface PatientsSelect<T extends boolean = true> {
  user?: T;
  DOB?: T;
  gender?: T;
  maritalStatus?: T;
  occupation?: T;
  race?: T;
  language?: T;
  emergencyContacts?:
    | T
    | {
        name?: T;
        relationship?: T;
        phone?: T;
        priority?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors_select".
 */
export interface DoctorsSelect<T extends boolean = true> {
  user?: T;
  DOB?: T;
  gender?: T;
  language?: T;
  bio?: T;
  specialties?:
    | T
    | {
        primary?: T;
        secondary?: T;
        procedures?: T;
        id?: T;
      };
  credentials?:
    | T
    | {
        medicalCertifications?:
          | T
          | {
              type?: T;
              institution?: T;
              date?: T;
              name?: T;
              id?: T;
            };
        licenses?:
          | T
          | {
              licenseNumber?: T;
              type?: T;
              status?: T;
              issuingState?: T;
              expirationDate?: T;
              id?: T;
            };
        boardCertifications?:
          | T
          | {
              boardName?: T;
              certificationId?: T;
              status?: T;
              date?: T;
              expirationDate?: T;
              id?: T;
            };
        hospitalAffiliations?:
          | T
          | {
              name?: T;
              department?: T;
              roles?: T;
              startDate?: T;
              endDate?: T;
              id?: T;
            };
        isVerified?: T;
      };
  contact?:
    | T
    | {
        officialPhone?: T;
        officialEmail?: T;
        mobilePhone?: T;
      };
  metrics?:
    | T
    | {
        numberOfPatients?: T;
        readmissionRate?: T;
        experience?: T;
        rating?:
          | T
          | {
              user?: T;
              rating?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "healthStatuses_select".
 */
export interface HealthStatusesSelect<T extends boolean = true> {
  patient?: T;
  vitals?:
    | T
    | {
        bloodPressure?: T;
        heartRate?: T;
        temperature?: T;
        respiratoryRate?: T;
        oxygenSaturation?: T;
        weight?: T;
        bmi?: T;
      };
  complaint?: T;
  symptoms?:
    | T
    | {
        description?: T;
        severity?: T;
        duration?: T;
        onset?: T;
        id?: T;
      };
  pain?:
    | T
    | {
        location?: T;
        intensity?: T;
        type?: T;
        aggravatingFactors?: T;
        relievingFactors?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "histories_select".
 */
export interface HistoriesSelect<T extends boolean = true> {
  patient?: T;
  diseaseHistory?:
    | T
    | {
        name?: T;
        diagnosisDate?: T;
        resolved?: T;
        resolutionDate?: T;
        id?: T;
      };
  surgicalHistory?:
    | T
    | {
        procedure?: T;
        date?: T;
        facility?: T;
        id?: T;
      };
  familyHistory?:
    | T
    | {
        condition?: T;
        relation?: T;
        notes?: T;
        id?: T;
      };
  allergies?:
    | T
    | {
        substance?: T;
        reaction?: T;
        severity?: T;
        onsetDate?: T;
        lastReactionDate?: T;
        id?: T;
      };
  socialHistory?:
    | T
    | {
        smoking?:
          | T
          | {
              status?: T;
              years?: T;
              quiteDate?: T;
              lastUser?: T;
            };
        alcohol?:
          | T
          | {
              status?: T;
              years?: T;
              quiteDate?: T;
              lastUser?: T;
            };
        substanceUse?:
          | T
          | {
              substances?: T;
              status?: T;
              quiteDate?: T;
              lastUser?: T;
            };
      };
  exercise?: T;
  diet?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "diagnoses_select".
 */
export interface DiagnosesSelect<T extends boolean = true> {
  appointment?: T;
  patient?: T;
  doctor?: T;
  healthStatus?: T;
  history?: T;
  chiefComplaint?: T;
  preAppointmentNotes?: T;
  medicationsReviewed?: T;
  templateUsed?: T;
  onsetDate?: T;
  dateResolved?: T;
  status?: T;
  updatedBy?: T;
  differentialDiagnosis?:
    | T
    | {
        condition?: T;
        icd10Code?: T;
        reasoning?: T;
        isPrimary?: T;
        confidence?: T;
        laterality?: T;
        severity?: T;
        dateConfirmed?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reminders_select".
 */
export interface RemindersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments_select".
 */
export interface AppointmentsSelect<T extends boolean = true> {
  patient?: T;
  doctor?: T;
  diagnosis?: T;
  healthStatus?: T;
  reminders?: T;
  reason?: T;
  type?: T;
  status?: T;
  confirmation?:
    | T
    | {
        isConfirmed?: T;
        confirmedAt?: T;
        confirmedBy?: T;
      };
  cancellation?:
    | T
    | {
        cancelledAt?: T;
        cancelledBy?: T;
        reason?: T;
      };
  startTime?: T;
  endTime?: T;
  patientNotes?: T;
  doctorNotes?: T;
  followUpInstructions?: T;
  consentLevels?: T;
  isEmergency?: T;
  online?:
    | T
    | {
        url?: T;
        accessCode?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  appointment?: T;
  body?: T;
  status?: T;
  refMessage?: T;
  from?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referrals_select".
 */
export interface ReferralsSelect<T extends boolean = true> {
  appointment?: T;
  from?: T;
  to?: T;
  reason?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recurrencePlans_select".
 */
export interface RecurrencePlansSelect<T extends boolean = true> {
  supervisor?: T;
  appointment?: T;
  name?: T;
  frequency?: T;
  interval?: T;
  startDate?: T;
  endDate?: T;
  startTime?: T;
  endTime?: T;
  weekDays?: T;
  exceptions?:
    | T
    | {
        date?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}